export * from "./StepNumBg";
export { default as Bricks } from "./bricks.png";
export * from "./LeftCurly";
export * from "./RightCurly";
export * from "./EmptyHistory";
export { default as Logo } from "./logo.png";
export { default as Tail } from "./tail.png";
export { default as Head } from "./head.png";
export { default as HeroImage } from "./hero-image.png";
export { default as ChooseCoin } from "./choose-coin.png";
export { default as EmptyCoin } from "./empty-coin.PNG";
export { default as SpinningCoin } from "./spinning-coin.gif";
export { default as MarioDraco } from "./mario-draco.jpeg";
export * from "./Telegram";
export * from "./Twitter";
export * from "./HouseSolid";
